$color =rgb(31, 31, 31)
$inner_color =rgb(31, 31, 31)
$outer_color = rgba(246, 193, 152, 1)
$font_color =rgb(212, 212, 212)
$placeholder_color =rgb(127, 127, 127)
$check_color = rgba(142, 218, 197, 1)
