#!/bin/bash

export PATH="$HOME/.local/share/omarchy/bin:$PATH"

# Set to true when going directly to a submenu, so we can exit directly
BACK_TO_EXIT=false

back_to() {
  local parent_menu="$1"

  if [[ "$BACK_TO_EXIT" == "true" ]]; then
    exit 0
  elif [[ -n "$parent_menu" ]]; then
    "$parent_menu"
  else
    show_main_menu
  fi
}

menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-c" "$index")
    fi
  fi

  echo -e "$options" | omarchy-launch-walker --dmenu --width 295 --minheight 1 --maxheight 600 -p "$prompt…" "${args[@]}" 2>/dev/null
}

terminal() {
  xdg-terminal-exec --app-id=com.omarchy.Omarchy "$@"
}

present_terminal() {
  omarchy-launch-floating-terminal-with-presentation $1
}

open_in_editor() {
  notify-send "Editing config file" "$1"
  omarchy-launch-editor "$1"
}

install() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm $2"
}

install_and_launch() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm $2 && setsid gtk-launch $3"
}

install_font() {
  present_terminal "echo 'Installing $1...'; sudo pacman -S --noconfirm --needed $2 && sleep 2 && omarchy-font-set '$3'"
}

install_terminal() {
  present_terminal "omarchy-install-terminal $1"
}

aur_install() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2"
}

aur_install_and_launch() {
  present_terminal "echo 'Installing $1 from AUR...'; yay -S --noconfirm $2 && setsid gtk-launch $3"
}

show_learn_menu() {
  case $(menu "Learn" "  Keybindings\n  Omarchy\n  Hyprland\n󰣇  Arch\n  Neovim\n󱆃  Bash") in
  *Keybindings*) omarchy-menu-keybindings ;;
  *Omarchy*) omarchy-launch-webapp "https://learn.omacom.io/2/the-omarchy-manual" ;;
  *Hyprland*) omarchy-launch-webapp "https://wiki.hypr.land/" ;;
  *Arch*) omarchy-launch-webapp "https://wiki.archlinux.org/title/Main_page" ;;
  *Bash*) omarchy-launch-webapp "https://devhints.io/bash" ;;
  *Neovim*) omarchy-launch-webapp "https://www.lazyvim.org/keymaps" ;;
  *) show_main_menu ;;
  esac
}

show_trigger_menu() {
  case $(menu "Trigger" "  Capture\n  Share") in
  *Capture*) show_capture_menu ;;
  *Share*) show_share_menu ;;
  *) show_main_menu ;;
  esac
}

show_capture_menu() {
  case $(menu "Capture" "  Screenshot\n  Screenrecord\n󰃉  Color") in
  *Screenshot*) omarchy-cmd-screenshot smart ;;
  *Screenrecord*) show_screenrecord_menu ;;
  *Color*) pkill hyprpicker || hyprpicker -a ;;
  *) show_trigger_menu ;;
  esac
}

show_screenrecord_menu() {
  case $(menu "Screenrecord" "  Region\n  Region + Audio\n  Display\n  Display + Audio\n  Display + Webcam") in
  *"Region + Audio"*) omarchy-cmd-screenrecord region --with-audio ;;
  *Region*) omarchy-cmd-screenrecord ;;
  *"Display + Audio"*) omarchy-cmd-screenrecord output --with-audio ;;
  *"Display + Webcam"*) omarchy-cmd-screenrecord output --with-audio --with-webcam ;;
  *Display*) omarchy-cmd-screenrecord output ;;
  *) back_to show_capture_menu ;;
  esac
}

show_share_menu() {
  case $(menu "Share" "  Clipboard\n  File \n  Folder") in
  *Clipboard*) terminal bash -c "omarchy-cmd-share clipboard" ;;
  *File*) terminal bash -c "omarchy-cmd-share file" ;;
  *Folder*) terminal bash -c "omarchy-cmd-share folder" ;;
  *) back_to show_trigger_menu ;;
  esac
}

show_setup_menu() {
  local options="  Audio\n  Wifi\n󰂯  Bluetooth\n󱐋  Power Profile\n󰍹  Monitors"
  [ -f ~/.config/hypr/bindings.conf ] && options="$options\n  Keybindings"
  [ -f ~/.config/hypr/input.conf ] && options="$options\n  Input"
  options="$options\n  Defaults\n󰱔  DNS"

  case $(menu "Setup" "$options") in
  *Audio*) xdg-terminal-exec --app-id=com.omarchy.Wiremix -e wiremix ;;
  *Wifi*)
    rfkill unblock wifi
    omarchy-launch-wifi
    ;;
  *Bluetooth*)
    rfkill unblock bluetooth
    bluetui
    ;;
  *Power*) show_setup_power_menu ;;
  *Monitors*) open_in_editor ~/.config/hypr/monitors.conf ;;
  *Keybindings*) open_in_editor ~/.config/hypr/bindings.conf ;;
  *Input*) open_in_editor ~/.config/hypr/input.conf ;;
  *Defaults*) open_in_editor ~/.config/uwsm/default ;;
  *DNS*) present_terminal omarchy-setup-dns ;;
  *) show_main_menu ;;
  esac
}

show_setup_power_menu() {
  profile=$(menu "Power Profile" "$(omarchy-powerprofiles-list)" "" "$(powerprofilesctl get)")

  if [[ "$profile" == "CNCLD" || -z "$profile" ]]; then
    back_to show_setup_menu
  else
    powerprofilesctl set "$profile"
  fi
}

show_install_menu() {
  case $(menu "Install" "󰣇  Package\n󰣇  AUR\n  Web App\n  TUI\n") in
  *Package*) terminal omarchy-pkg-install ;;
  *AUR*) terminal omarchy-pkg-aur-install ;;
  *Web*) present_terminal omarchy-webapp-install ;;
  *TUI*) present_terminal omarchy-tui-install ;;
  *) show_main_menu ;;
  esac
}

show_remove_menu() {
  case $(menu "Remove" "󰣇  Package\n  Web App\n  TUI\n") in
  *Package*) terminal omarchy-pkg-remove ;;
  *Web*) present_terminal omarchy-webapp-remove ;;
  *TUI*) present_terminal omarchy-tui-remove ;;
  *) show_main_menu ;;
  esac
}

show_update_menu() {
  case $(menu "Update" " Omarchy\n󰸌  Theme\n󰇅  Hardware\n  Firmware\n  Password\n  Timezone\n  Time") in
  *Omarchy*) present_terminal omarchy-update ;;
  *Hardware*) show_update_hardware_menu ;;
  *Firmware*) present_terminal omarchy-update-firmware ;;
  *Timezone*) present_terminal omarchy-tz-select ;;
  *Time*) present_terminal omarchy-update-time ;;
  *Password*) show_update_password_menu ;;
  *Theme*) omarchy-theme-set jvvesper ;;
  *) show_main_menu ;;
  esac
}

show_update_process_menu() {
  case $(menu "Restart" "  Hypridle\n  Hyprsunset\n  Swayosd\n󰌧  Walker\n󰍜  Waybar") in
  *Hypridle*) omarchy-restart-hypridle ;;
  *Hyprsunset*) omarchy-restart-hyprsunset ;;
  *Swayosd*) omarchy-restart-swayosd ;;
  *Walker*) omarchy-restart-walker ;;
  *Waybar*) omarchy-restart-waybar ;;
  *) show_update_menu ;;
  esac
}

show_update_hardware_menu() {
  case $(menu "Restart" "  Audio\n󱚾  Wi-Fi\n󰂯  Bluetooth") in
  *Audio*) present_terminal omarchy-restart-pipewire ;;
  *Wi-Fi*) present_terminal omarchy-restart-wifi ;;
  *Bluetooth*) present_terminal omarchy-restart-bluetooth ;;
  *) show_update_menu ;;
  esac
}

show_update_password_menu() {
  case $(menu "Update Password" "  Drive Encryption\n  User") in
  *Drive*) present_terminal omarchy-drive-set-password ;;
  *User*) present_terminal passwd ;;
  *) show_update_menu ;;
  esac
}

show_system_menu() {
  case $(menu "System" "  Lock\n󰜉  Restart\n󰐥  Shutdown") in
  *Lock*) omarchy-lock-screen ;;
  *Restart*) omarchy-state clear re*-required && systemctl reboot --no-wall ;;
  *Shutdown*) omarchy-state clear re*-required && systemctl poweroff --no-wall ;;
  *) back_to show_main_menu ;;
  esac
}

show_main_menu() {
  go_to_menu "$(menu "Go" "󰀻  Apps\n󰉉  Install\n󰭌  Remove\n  Update\n  Setup\n󱓞  Trigger\n󰧑  Learn\n  About\n  System")"
}

go_to_menu() {
  case "${1,,}" in
  *apps*) walker -p "Launch…" ;;
  *share*) show_share_menu ;;
  *install*) show_install_menu ;;
  *remove*) show_remove_menu ;;
  *setup*) show_setup_menu ;;
  *trigger*) show_trigger_menu ;;
  *screenshot*) show_screenshot_menu ;;
  *screenrecord*) show_screenrecord_menu ;;
  *power*) show_setup_power_menu ;;
  *update*) show_update_menu ;;
  *learn*) show_learn_menu ;;
  *about*) omarchy-launch-about ;;
  *system*) show_system_menu ;;
  esac
}

if [[ -n "$1" ]]; then
  BACK_TO_EXIT=true
  go_to_menu "$1"
else
  show_main_menu
fi